# Generated by Django 5.2.8 on 2025-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome do item')),
                ('descricao', models.TextField(verbose_name='Descrição do item')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Foto do item')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESGATADO', 'Resgatado')], default='DISPONIVEL', max_length=10, verbose_name='Status do item')),
                ('data_encontrado', models.DateField(verbose_name='Data Item Encontrado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
        ),
    ]
